/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#ffb86b',
        'outline': '#71787d',
        'surface-dim': '#b1e0ff',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-background': '#001e2d',
        'surface-container-high': '#d1ecff',
        'surface': '#f5faff',
        'inverse-primary': '#9ecde9',
        'secondary': '#895100',
        'background': '#f5faff',
        'on-surface-variant': '#41484c',
        'error': '#ba1a1a',
        'on-secondary-fixed': '#2c1700',
        'secondary-container': '#ffa024',
        'tertiary': '#002838',
        'on-primary-fixed': '#001e2c',
        'surface-container': '#ddf0ff',
        'inverse-on-surface': '#e3f3ff',
        'inverse-surface': '#00344a',
        'outline-variant': '#c1c7cd',
        'surface-bright': '#f5faff',
        'on-surface': '#001e2d',
        'primary-container': '#043f56',
        'secondary-fixed': '#ffdcbc',
        'on-secondary-container': '#693d00',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#9ecde9',
        'surface-container-highest': '#c5e7ff',
        'primary-fixed': '#c3e8ff',
        'primary': '#002839',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-tint': '#35647c',
        'surface-container-low': '#e9f5ff',
        'on-primary-container': '#7caac5',
        'tertiary-container': '#003f56',
        'surface-variant': '#c5e7ff',
        'on-secondary-fixed-variant': '#683d00',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'Georgia', 'serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['"Work Sans"', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      backgroundImage: {
        'editorial-gradient': 'linear-gradient(135deg, #002839 0%, #043f56 100%)',
      },
      boxShadow: {
        'ambient': '0 20px 50px rgba(0, 30, 45, 0.08)',
        'editorial': '0 4px 30px rgba(0, 40, 57, 0.15)',
      },
    },
  },
  plugins: [],
};
